### ISSUE TITLE
Implement adding collections to collections (like mods)

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX.Web-Frontend#58]
Feedback Set3

 

Feedback Set2

- [x]  Loading collection with 2 collections into playlist and deleting one, causes browser to get stuck
 1. Load collection with two collections
 2. Remove one colleciton
 3. Save Collection in PLaylist
 4. Observe Save button remains active
 5. Try to close and open PL
 ( On the second attempt, the save button did not work: https://gyazo.com/68e3fab88a8a62ac4c3039a7dccfd263)

Feedback Set1
- [x] Loading a collection into the playlist detects changes (shows save/undo)
- [x] Collection items should be called "MODS" instead of "DEPENDENCIES" (The mods have dependenices)
- [x] Remove Version selection for Collections until versioning is properly implemented
- [x] The newly created collection should be loaded into the playlist after saving

Checklist
- [x] Prevent infinite recursion loop in client for collections inside collections which has any parent collection inside the collection :)
- [x] Disallow adding a collection to itself.
- [x] Update client support
- [x] Update dependency editor view support (not yet search+add; use the playlist for now)
- [x] Add support for non-network mods in Collections in Playlist
- [x] Fix showing dependencies of dependencies
- [x] Fix adding collections with 10+ mods into the playlist (and mods with 10+ deps)
- [x] Add + Button To collection cards
- [x] Allow Collections to be collapsed in Playlist view and expanded
- [x] Show Collection Title like Mod titles ( Name, Image, Author)
- [x] Remove Server connection when other collections are added
- [x] Allow Forking to combine Collections

Potential issues

- Collections with more than x will blow up the Playlist dependency query.
 - Paginate/VirtualScroll?
 - Additionally: Make loading the dependencies something that only happens on expanding the dependency area
 - Caching the dependency sizes on Mods/Collections would be a nice optimization, however when combining elements into a Playlist/Collection, if we don't know each individual component, we can't deduplicate the size for mods that exist in several collections / dependency chains, and thus the overall size would be wrong?

**Comment by sickboy** [comment]
Addressed the collections with more than 100 mods issue preliminary in 257d27f879286f7cef06be13a369292b2b55b5ca

**Comment by Sonsalt** [comment]
Feedback Set1
- [ ] Collection items should be called "MODS" instead of "DEPENDENCIES" (The mods have dependenices)
- [ ] Hover over button on Banner does not fit 100% lower part 1 Pixel too high
- [ ] Remove Version selection for Collections until versioning is properly implemented
- [ ] Saving Collection with attached collections removes almost all content and clears the playlist

**Comment by sickboy** [comment]
@Sonsalt 

2. Nothing to do with this card?
4. Nothing to do with this card? - When you save a playlist then it empties out right? Or did we load the collection back in, I dont remember.

**Comment by Sonsalt** [comment]
@sickboy 

Why does Nr.1 have nothing to do with this card? It is about how the collections should display their content in the playlist... 

Regarding Nr.2 When saving a playlist as a collection it should keep the items in the playlist but change the status from playlist to loaded collection, so that further changes can be saved to the collection. In this case it however does not even properly save the content.

**Comment by Sonsalt** [comment]
@sickboy 

Re Nr.2 It is currently possible to select a version for a loaded collection, just like a mod. However the Author of a collection has no control over his versions, thus the ability to lock versions and select individual versions for collections is not working. 

Re 4. When Selecting multiple collections into the playlist and saving the playlist, The content is not properly saved. The saved Collection only has 2-3 mods instead of all the mods of the 2 Collections. 

Plus, The playlist is empty after saving it to collection. It should however remain, just change the status, to show that it is now a loaded collection. The user can then further change the playlist items and save them to the collection.

**Comment by sickboy** [comment]
> Re 4. When Selecting multiple collections into the playlist and saving the playlist, The content is not properly saved. The saved Collection only has 2-3 mods instead of all the mods of the 2 Collection

I guess you missed on Skype:
> What's missing is full support for the Collection -> Content detail page + Editor. So you're left to doing stuff through the Playlist for now. But that should be not too much effort :)

Also added to the description:
> Show the embedded collections inside the Collection Content section

> Plus, The playlist is empty after saving it to collection. It should however remain, just change the status, to show that it is now a loaded collection. The user can then further change the playlist items and save them to the collection.

That's by design. It's fine if you want to change that, but it's not a bug of this card.

**Comment by sickboy** [comment]
I've also found and added
- [ ] Loading a collection into the playlist detects changes (shows save/undo)

**Comment by sickboy** [comment]
@Sonsalt again can't reproduce
